name: Lift3d_Map_GNN
instantiate_config:
  _target_: MapPolicy.models.SingleFrame_Lift3d_GNN
  point_cloud_encoder:
    _target_: MapPolicy.models.LIFT3D.lift3d.models.lift3d.model_loader.lift3d_clip_base
  map_constructor:
    _target_: MapPolicy.models.map_models.map_constructor.ParameterEstimator_SingleFrame_Regularization
    _partial_: true
    map_name: ${task_name}
    device: ${device}
  map_encoder:
    _target_: MapPolicy.models.map_models.GNN_encoder.RoboGraphormer
    map_name: ${task_name}
    hidden_dim: 768
    num_layers: 6
    num_heads: 24
  loss_map_construction:
    _target_: MapPolicy.loss.point_cloud_complementation.unidirectional_chamfer_loss
    _partial_: true
  policy_hidden_dims: [256, 256, 256]
  policy_head_init_method: orthogonal